### ISSUE TITLE
automatic offset calculation is broken for pixel aligned rendering

### ISSUE THREAD

**Issue by imagico** [imagico/jsdotpattern#1]
When loading a symbol offsets are calculated automatically based on the symbol bounding box.  This however does not work together with pixel aligned rendering at the moment - you need to manually specify the correct offset to get proper pixel aligned rendering for most symbols.

**Comment by pnorman** [comment]
When converting to pixel aligned the patterns are placed at x.5 in the SVG - placing them at x.0 instead would fix this
