### ISSUE TITLE
Deselecting default symbol does not work

### ISSUE THREAD

**Issue by daganzdaanda** [imagico/jsdotpattern#11]
To reproduce:

- open a new window with https://imagico.de/map/jsdotpattern.php
- generate a random dot pattern
- click render to see the pattern with the default tree symbol
- select an additional symbol with the + button, it will deselect the "use" indicator at the default symbol
- render the pattern now with 2 symbols, looks good!
- deselect the default symbol by clicking the + button, now only your second symbol is selected
- render the pattern again: it will be only using the default tree symbol, and not the selected symbol

This also happens if you select the "use" button on any symbol and add other symbols. When you remove the previously "use"d symbol, the whole pattern switches back to the default tree.

**Comment by imagico** [comment]
I can confirm this is happening, thanks for reporting.

**Comment by imagico** [comment]
Should be fixed with https://github.com/imagico/jsdotpattern/commit/38aa30914dd5321359f590fd17ee9cbb6458485d.

**Comment by daganzdaanda** [comment]
Hi, there still seems to be a bug:

- Select another symbol than the default to "use"
- Add some other symbols with "+" and render -- all's fine.
- remove the symbol that you chose to "use" and render -- everything's a tree again 🙂
