### ISSUE TITLE
Faster clipping

### ISSUE THREAD

**Issue by sommerluk** [imagico/jsdotpattern#9]
Currently I’m playing around with svg_pattern.sh to clip  an SVG pattern. The very same pattern has to be clipped to various sizes. It seems like the most slow part is sanitizing, and not clipping. I would like to sanitze only once the SVG pattern. And later clip/cut various sizes of this pattern. Currently I always run svg_pattern.sh with the hole sanitizing process. Would it be possible to clip a pattern without sanitizing? In a separate script? Or add an option to svg_pattern.sh to run it without the sanitizing?

**Comment by imagico** [comment]
Good point.  This is fairly easy for you to change in the script ad hoc (by either removing the `sed` and what comes after for sanitization only or the inkscape calls before the `sed` for clipping only).

**Comment by sommerluk** [comment]
That’s easy indeed. (I wasn’t sure if it’s so easy before.) So here comes created svg_pattern_clip.sh that does only clipping. Here’s the code:

```
#!/bin/sh
# ------------------------------------------------------------
#  clip a jsdotpattern produced SVG for use with Mapnik
# ------------------------------------------------------------

SRC="$1"
TARGET="$2"
CLIP="$3"

if [ -z "$1" ] || [ -z "$2" ] ; then
	echo "Usage: $0 <input> <output> <clip_width>"
	echo "This script clips an SVG pattern (that has to be yet sanitized"
	echo "with svg_pattern.sh) to a given width."
	echo "Warning: do not use this on SVGs not generated with jsdotpattern,"
	echo "         it likely don't work"
	exit
fi

SIZE=`grep "width" "$SRC" | head -n 1 | sed "s?\"??g;s?.*width=\([0-9]*\).*?\1?"`

if [ -z "$SIZE" ] ; then
	echo "Error: pattern size could not be read from source SVG."
fi

if [ -z "$CLIP" ] ; then
	CLIP="$SIZE"
fi

cp "$SRC" "$TARGET"

# this is pretty whacky since it depends on the specific structure of the file (specifically the presence of a <desc> tag at the very end)
sed -i -e "s?<desc?<rect width=\"$SIZE\" height=\"$CLIP\" rx=\"0\" x=\"0\" y=\"0\" id=\"rect8566\" style=\"fill:none;fill-opacity:1;stroke:none\" /><desc?" "$TARGET"

inkscape -g --verb EditSelectAll --verb SelectionIntersect \
		--verb FileSave --verb FileClose \
		--verb FileQuit "$TARGET"

inkscape -z --vacuum-defs -l "$TARGET" -f "$TARGET"

```

Maybe it might be interesting to add it to this repository…

**Comment by imagico** [comment]
Clipping only is now supported through https://github.com/imagico/jsdotpattern/commit/2910194c9af6fd38faa32b1ec11f3810f7eafcf9 by means of analyzing the SVG content and automatically choosing not to perform the sanitizing step if the SVG looks to be processed already.

**Comment by sommerluk** [comment]
Thanks, that’s great!

2017-08-13 10:18 GMT, Christoph Hormann <notifications@github.com>:
> Clipping only is now supported through
> https://github.com/imagico/jsdotpattern/commit/2910194c9af6fd38faa32b1ec11f3810f7eafcf9
> by means of analyzing the SVG content and automatically choosing not to
> perform the sanitizing step if the SVG looks to be processed already.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/imagico/jsdotpattern/issues/9#issuecomment-322033512


-- 
Lukas Sommer
